### ISSUE TITLE
Calculate next conversation due date for employee with multiple records

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1033]
Ticket separated from #1015
The employees with multiple records in the employee demo table should be addressed in a separate ticket, as they are special cases that still needs to be discussed.
These employees with 1 terminated record becomes an issue for the calc.

All Users with multiple entries can be found in this spreadsheet: https://bcgov.sharepoint.com/:x:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Multiple%20entries.xlsx?d=we25ba549bcbc4e62bcbf3e1995a11f7a&csf=1&web=1&e=zLkrBB

**Comment by Travis-A-Clark** [comment]
Likely also related to ticket #857 to deal with employees with multiple records in general.

**Comment by telusdcinco** [comment]
Additional issue to be addressed in this ticket.  In December 2022, conversation participants was reclassified into 2 roles (manager/employee).  The conversation due date calc process uses this information to determine the last conversation the employee is a part of.  Since December 2022, this process was not updated to check the role value (role = 'emp'.

**Comment by telusdcinco** [comment]
Check ..\storage\logs\CalcNextConversationDatge.log to verify process results.

**Comment by steffipravasi** [comment]
@telusdcinco I am not sure how to find test users for this ticket

**Comment by steffipravasi** [comment]
Test data used: 
159617	Dureault,Bronte
164312	Heatherington,Mackenzie
181150	Lenarduzzi,Sophia
71231	Dashwood,Barbara Anne

**Comment by steffipravasi** [comment]
Test data used on Sep 12:
159617	Dureault,Bronte
164312	Heatherington,Mackenzie
181150	Lenarduzzi,Sophia
71231	Dashwood,Barbara Anne
