### ISSUE TITLE
Exclude past employees in the email/in-app notification when creating goals in Sys/HR Admin Goal Bank

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#1058]
Exclude past employees in the email/in-app notification when creating goals in Sys/HR Admin Goal Bank

**Comment by steffipravasi** [comment]
Test data used: https://bcgov.sharepoint.com/:x:/r/teams/02915/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7Bbf10ad6e-fea4-4bcd-b4df-4dc602c46f92%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1
@telusdcinco I did validated the past users through the email I received but cannot verify the in-app since the notification page is giving error![Screenshot 2023-07-20 at 2.27.18 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/65b9dd2f-0906-46d5-a914-edc873d48e22)

**Comment by steffipravasi** [comment]
Created a new ticket for the Ajax error: #1074

**Comment by steffipravasi** [comment]
Test validated for email and in-app notifications.
