### ISSUE TITLE
Sys Security > Access Organizations: search filters return incorrect results

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1086]
Without applying any filters, the Access Organizations list displays some duplicate responses. See below that "Jobs, Economic Development and Innovation" is displayed on page 2 and again on page 4.

**Page 2**
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/3f06082f-148f-4131-afd8-7a3b526aca68)

**Page 4**
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c7762bcf-98df-45a7-a16e-768dd1e43491)

Applying the Allow Log-In sort option removes "Jobs, Economic Development and Innovation" from the results all together and adds a second copy of "Social Development and Poverty Reduction.

Applying the Allow In-App Message sort option creates a second version of "Agriculture and Food". 

Etc, etc.

Please review the logic and the consistency of the results displayed. Thank you!

**Comment by telusdcinco** [comment]
@jizhaogit Please review code changes for #1086.

**Comment by jizhaogit** [comment]
Thank you Dennis, looks good to me.

**Comment by steffipravasi** [comment]
@telusdcinco 
1) When sorting the column Allow Login, I checked the list of orgs on the first page, then navigated to 2,3,4. When navigated back to page 1, the list of orgs changed and now they are different. It was the same for all the pages. Can we fix the sorting order somehow? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0hiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37f00d064baf2b278506e20aa18fe46c5acba68d/Screenshot%202023-09-26%20at%202.24.16%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1BiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a390c2345ce9c272a662964116aace2e4c40cd37/Screenshot%202023-09-26%20at%202.35.42%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1hiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d12b6440a592d6c0fa23c957dcebf01a1a63ffd3/Screenshot%202023-09-26%20at%202.39.17%20PM.png)
2) The same issue happens when sorting Allow-In app and Allow email column(Ascending or descending doesn't matter)

**Comment by Travis-A-Clark** [comment]
@telusdcinco I'm still getting the same thing that Steffi previously mentioned. The order of results shifts every time you move between the four pages of results. Sort by "Allow In-app Message" and the first 10 results look like this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeklVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d77b1e97968836987ba41152ff70f6e1e4ce8578/image.png)


Navigate to pages 2, 3, or 4 of results and then return to page 1. The results are now different:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemNVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c84a7a1af323b1fa71f860706494cdb0729b1a90/image.png)

**Comment by telusdcinco** [comment]
@Travis-A-Clark Please retest in Test after clearing the browser cache.
