### ISSUE TITLE
I want to be able to notify participants when I have made an update to our conversation

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1102]
**Current Scenario**

A notification is generated when a conversation is created and when it is signed off. However, no notifications are sent if the content of the conversation has been updated.

**Desired Solution**

- [x] Add a "Send Notification" button to the top right of all open conversations. 

- [x] Include "i" info toggle tip that says: "Use this button to alert the other participant that you have made updates to this conversation."

- [x] Generate homepage alert for the other participant similar to one below that says: "_USER NAME_ has made updates to your conversation". Include title and date same as below.
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1102/image%20(3).png?csf=1&web=1&e=wtlpNU
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjArIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0035a923d8c0a2872795c24209b6b5c471f43497/image.png)

- [x] Generate an email alert for the other participant similar to above.

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
No sprints assigned
Estimate: 3
Epics: All - Notification & Communication

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Run 'php artisan migrate'

**Comment by steffipravasi** [comment]
@telusdcinco 
Issue: 
1) The users are not receiving the email notification. Only in-app notifications are received.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEtUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30f31fecba619cd9c97cf187b3318ab00f17b8e2/Screenshot%202024-02-27%20at%2012.51.25%E2%80%AFPM.png" alt="Screenshot 2024-02-27 at 12.51.25 PM.png" />
2) Can we add a validation to check if there are any updates made to the comments? So if there are changes made to the comments, then only trigger the notifications or else display a different message?

------------------------------------------------------------------------------
Questions for @jessicahjwu 
1) Should we change the message to 'Notifications to other participants have been sent'?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--986669edf503acaa86a5c76ac757f331f5f8da1d/Screenshot%202024-02-27%20at%2012.49.53%E2%80%AFPM.png" alt="Screenshot 2024-02-27 at 12.49.53 PM.png" />
2) Should we align the button to Save Comments? Do we need the button to be displayed on the top and bottom of the page?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a158edceffac9265d06a5cc6b7965bd96e5fe8b/Screenshot%202024-02-27%20at%2012.55.23%E2%80%AFPM.png" alt="Screenshot 2024-02-27 at 12.55.23 PM.png" />
3) Once the Send Notification button is clicked, it cannot be clicked again since the button is replaced with the Sent notifications to other participants message. I think the user must have the access to Send Notifications again?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20a08eee0016f572c9e66b5c5b4f4828a690295e/Screenshot%202024-02-27%20at%2012.49.53%E2%80%AFPM.png" alt="Screenshot 2024-02-27 at 12.49.53 PM.png" />
4) What if the user adds the comments -> Clicks on the button Send Notifications without Saving the comments -> Clicks on close button -> And selects Don't save option from the dialog box? 
Solution: We can add a validation to make the user save comments before hitting the Send notifications button

**Comment by jessicahjwu** [comment]
Thanks @steffipravasi! Please see the below:
1. Should we change the message to 'Notifications to other participants have been sent'? **Yes** 
2. Should we align the button to Save Comments? Do we need the button to be displayed on the top and bottom of the page? 
**Align the button to Save Comments - Yes** but I don't think it's necessary to display it on the top and bottom of the page.
3. Once the Send Notification button is clicked, it cannot be clicked again since the button is replaced with the Sent notifications to other participants message. I think the user must have the access to Send Notifications again? 
**Is it possible to have "re-send notifications" whilst the "notification sent" banner is still displayed?**
4. What if the user adds the comments -> Clicks on the button Send Notifications without Saving the comments -> Clicks on close button -> And selects Don't save option from the dialog box?
Solution: We can add a validation to make the user save comments before hitting the Send notifications button
**Agree - I think this scenario will need to trigger the same saving modal as when comments are being input. Or can the system checks first before sending the notification? I.e. User clicks on send notification before saving -> system prompts with "please save comments before sending"**. This will also prevent users from clicking on the wrong button

**Comment by jizhaogit** [comment]
@steffipravasi i remember the conversation notification/email logic has been changed before by a ticket that only trigger the notification.  would you please help check back?

**Comment by steffipravasi** [comment]
Robinson,sheila does not receive emails
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODQzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4180ef2b5e919bf8e28bc5ba7806025e566929c7/Screenshot%202024-04-04%20at%203.59.18%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 3.59.18 PM.png" />

**Comment by steffipravasi** [comment]
Emails are received now. Functionality working as expected.
<img width="1779" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkU0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd05f925bf95a9ee7d866e56cf87a5435b29dea8/Screenshot%202024-04-04%20at%204.31.52%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 4.31.52 PM.png" />

**Comment by jessicahjwu** [comment]
Hi @telusdcinco, I think previously we agreed to align the "send notification" button with the "save comments" button so it's more noticeable, can we have the "send notification" button placed on the highlighted spot?
<img width="1222" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b37e8b061f59e06daaef4b0cb003ee789624e8b6/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
Button position updated
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b4c6fb049c8b4f95a0ead9513558c5f94ed8e4f/Screenshot%202024-04-12%20at%202.58.34%E2%80%AFAM.png" alt="Screenshot 2024-04-12 at 2.58.34 AM.png" />
<img width="1814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79d92c98332a6a7c53ee9300eadb25a609485614/Screenshot%202024-04-12%20at%202.58.50%E2%80%AFAM.png" alt="Screenshot 2024-04-12 at 2.58.50 AM.png" />
<img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08b5f06638046ab733ddda80af497054c5e2cf76/Screenshot%202024-04-12%20at%202.59.11%E2%80%AFAM.png" alt="Screenshot 2024-04-12 at 2.59.11 AM.png" />

**Comment by steffipravasi** [comment]
Button position updated
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b4c6fb049c8b4f95a0ead9513558c5f94ed8e4f/Screenshot%202024-04-12%20at%202.58.34%E2%80%AFAM.png" alt="Screenshot 2024-04-12 at 2.58.34 AM.png" />
<img width="1814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79d92c98332a6a7c53ee9300eadb25a609485614/Screenshot%202024-04-12%20at%202.58.50%E2%80%AFAM.png" alt="Screenshot 2024-04-12 at 2.58.50 AM.png" />
<img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08b5f06638046ab733ddda80af497054c5e2cf76/Screenshot%202024-04-12%20at%202.59.11%E2%80%AFAM.png" alt="Screenshot 2024-04-12 at 2.59.11 AM.png" />
