### ISSUE TITLE
In prod, the supervisor does not have "My Team" access even after the direct reports have selected her from the dropdown list

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1168]
Nicole De Greef, who is currently on a double-bunked position (00126621) does not have the option of "My Team" even after her employees have selected her as their supervisor in PROD. However, this information is different from Training and Test:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--688c799210e59308f94660505d5740773b04230c/image.png)
Despite the above, Nicole still seems to have the option of starting conversation with her direct reports in PROD:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--421daf9e1c32edd9cc173e39e3a6719a50fb8fd3/image.png)

We need to check and see what affected her ability of accessing "My Team" page.

**Comment by jessicahjwu** [comment]
Checked with Travis, this is likely linked to 1166.

**Comment by Travis-A-Clark** [comment]
@jizhaogit I know you did some work on #1166 to debug the rules around who is displayed on the My Team page for supervisors. Was hoping this might the same fix since this is another case where the functions all work (conversation participants, etc) but the person isn't displayed. One difference: this user, Nicole de Greef, has not been given the correct access permissions at all. When I manually enter the URL for the My Team page when using her profile in PROD, I get a 403 lack of access error.

**Comment by Travis-A-Clark** [comment]
@jessicahjwu @jizhaogit 

Ignore my previous message. Ticket 1166 has not been pushed to Training yet, so wouldn't account for why Nicole de Greef can see her direct reports in Training but not in Production.

This is a new mystery that only exists in production. That always makes it more difficult to troubleshoot, unfortunately, since we can't recreate in test or training.

**Comment by Travis-A-Clark** [comment]
Likely related to ticket #1171

**Comment by steffipravasi** [comment]
@jizhaogit I checked this case on the Test region and still see the same. Nicole cannot see the My Team section even after the employee selects her as the Current supervisor. 
Is our fix only applicable to Prod region?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40ffa1aa1fa14c22ea9560700d64879898f7b9f8/Screenshot%202023-11-30%20at%202.54.46%E2%80%AFPM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0VpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35f69b1739a6b6c1fefa133bb28406593777b5aa/Screenshot%202023-11-30%20at%202.54.32%E2%80%AFPM.png)

**Comment by jessicahjwu** [comment]
This doesn't seem like a standalone case as I had another person reaching out in the same situation (in Test/ Training they have the My Team page, but in PROD they're missing the option whilst having list of people reporting to them in-app). Name of the Supervisor is Jenni McConnell.
[Private Zenhub Image]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fdbdd55adb22d8a240ab4c5024f243ff99d47fb/image.png)
(https://api.zenhub.com/a
ttachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f90a5a61a232fa0d95956f180259b28d1480e566/image.png)

Is there a way to check how the two fields "role assigned" v.s. "# of direct reports/ shared reports" so we can understand if there are more users having the same issue?
