### ISSUE TITLE
Wrong user name displayed in goal update notifications; unnecessary notifications being sent

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1176]
**Current Scenario**

Employee: Kavi Gorana
Supervisor: Jessica Wade

1. Kavi creates a goal and shares that goal with Jessica. 
2. Jessica goes in to My Team page and clicks on Kavi's name to access Kavi's profile.
3. Jessica adds comments to the goal that Kavi shared with her.

The action is tracked correctly in the audit log.
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1176/image.png?csf=1&web=1&e=ArgF1n
<img width="547" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWN0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdc3248ea08c10c170442d1948f88542fda8d285/image.png" alt="image.png" />
<br>

The notifications are displayed correctly on Kavi's homepage.
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1176/image%20(1).png?csf=1&web=1&e=dKnien
<img width="754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW90QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21f8a1575430b68d833f42de304926de656cc77a/image.png" alt="image.png" />
<br>
<br>

However, the notifications are incorrect on Jessica's homepage and email notification. They show that Kavi made the comment when in fact it was Jessica that made the comment. Jessica should not be receiving any notification since she is the one that made the comment in the first place.
https://bcgov.sharepoint.com/:i:/r/teams/02915/Shared%20Documents/Product%20Team/Tickets%20Requirements/1176/image%20(2).png?csf=1&web=1&e=vD2PDA
<img width="612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTB0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a5987c0712b6a522ccb188ac6ea37517a10ee43/image.png" alt="image.png" />

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
Sprints: Feb 12-23, 2024

**Comment by jizhaogit** [comment]
addressed, please help verify in test. thanks

**Comment by steffipravasi** [comment]
@jizhaogit I followed the steps added in the ticket and noticed that the supervisor still receives the notification of comment added to goal which he/she has added
Supervisor: Shawna Wilson
Employee: Nichols Lisa
Expected results: Supervisor should not be receiving any notification since she is the one that made the comment in the first place.
<img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0xoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cc2cb0971a5353e63d4fa8dd6b1c72a9fb1fbfc/Screenshot%202024-01-19%20at%201.43.51%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 1.43.51 PM.png" />
<img width="1014" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2ZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63df397391e793c1d99f5b7bd045dbb3ea099cc1/Screenshot%202024-01-19%20at%201.45.42%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 1.45.42 PM.png" />

**Comment by steffipravasi** [comment]
@jizhaogit I added this because I saw this requirement in the description. If we want we can separate this to another ticket.
<img width="1578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEhwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ec31691b2912b9161e4c33834ce7d35d7ae2d31/Screenshot%202024-01-22%20at%202.38.56%E2%80%AFPM.png" alt="Screenshot 2024-01-22 at 2.38.56 PM.png" />

**Comment by jizhaogit** [comment]
it must be an old bug that create a notification to the comment submitter.  but since it is not the purpose for this ticket. can you please help separate it so that it will easy for us to track the changes?  thank you!

**Comment by jizhaogit** [comment]
@steffipravasi  i added notification and email restriction features in the goal comments function. can you please help verify from test? thanks!

**Comment by steffipravasi** [comment]
Test validated. Notifications looks good as per the ticket requirements.

**Comment by telusdcinco** [comment]
@jessicahjwu @jizhaogit
#1176 changes exist in non-prod but is not found in Prod.  Was #1176 deployed to Prod, it seemed the log above jumped from Deploy to Training then to Done status.

@jizhaogit  Please confirm by comparing GoalController.php between non-prod and Prod.

**Comment by jizhaogit** [comment]
@telusdcinco  Hi Dennis, i did the comparison for #1176 between training and prod. they both are same code base.  and i found a deployment history in prod for #1176 which is happened 5 months ago, the deployment id is a66ccdc0.

**Comment by jizhaogit** [comment]
@telusdcinco the is one piece of change for #1176 is found in test but not be pushed to training and prod. the deployment id is fc50b7e0

**Comment by telusdcinco** [comment]
@jessicahjwu @jizhaogit 

Missing #1176 item deployed to Training.
https://github.com/bcgov/performance/commit/fc50b7e0e49ea5aaf7a34c63b45d9d6099ab8c71
