### ISSUE TITLE
Supervisors with direct reports not seeing My Team page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1186]
Sounds like a repeat of ticket #1174.

Employee: Jill Inget (eID 134979) Inget,Jill	Jill.Inget@gov.bc.ca
Supervisor: Kiersten Fisher (eID 132836) Fisher,Kiersten	Kiersten.Fisher@gov.bc.ca
Jill selected Kiersten from the supervisor dropdown list:

<img width="424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXRjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0618d5b4b85c656b5582984221f88257232522bc/image.png" alt="image.png" />

Kiersten can see Jill in the conversation participant list:

<img width="233" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f166b7f16dee1febd4465daed48b3ee374a60aa/image.png" alt="image.png" />

But Kiersten does not have access to the My Team page at all:

<img width="262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--142fede894c548af5114cf26d59a05780fdf8af3/image.png" alt="image.png" />

**Comment by jizhaogit** [comment]
in this case, the reportees number for Kiersten in users_annex table is 0. but there are 2 available employees in users table that is reporting to her/him, details show as below:
mysql> select id, employee_id,name,excused_flag from users where reporting_to = '21211';
+-------+-------------+-----------------+--------------+
| id    | employee_id | name            | excused_flag |
+-------+-------------+-----------------+--------------+
| 21836 | 134979      | Jill Inget      |         NULL |
| 39550 | 174196      | Cynthia Drumond |         NULL |
+-------+-------------+-----------------+--------------+
2 rows in set (0.00 sec)

mysql> select date_deleted from employee_demo where employee_id in (134979,174196);
+--------------+
| date_deleted |
+--------------+
| NULL         |
| NULL         |
+--------------+
2 rows in set (0.02 sec)

the fix for #1174 need to be modified because it was rely on "reportees" in users_annex table.

**Comment by jizhaogit** [comment]
@Travis-A-Clark I applied a new fix for not only check users_annex table reportees but also check reporting_to from users table. and the issue is addressed. please help verify from your side. thanks!

**Comment by steffipravasi** [comment]
Employee 168981 | Kirby,Michelle | Michelle.Kirby@gov.bc.ca
reports to Robertson,Mara Tatiana  | 121065 |  Tatiana.Robertson@gov.bc.ca
i) Michelle did not have Mara selected as current supervisor
ii) The supervisor Mara has 14 direct reportees but couldn't see the My team section on her profile
iii) When the user Michelle selected Mara as the current supervisor -> Refreshed the page
iv) Then MAra's profile displayed the My Team section

**Comment by Travis-A-Clark** [comment]
As discussed, this is a temporary fix that will need to be run manually every day to keep up with any new cases. Ji will coordinate with Dennis once Dennis is back to come up with a broader fix.
