### ISSUE TITLE
504 Gateway Error when running Goals Summary Reports

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1200]
HR Administrator at Justice tried running the Goals Summary reports with the following scenario:
"I tried Justice > Corporate Management Services Branch - the first two levels worked. Then, when I tried going into any part of CMSB (into level 3 & 4) I got the Error 504 message"

I tried and was able to re-create the same issue, 504 Gateway Error message appeared when trying to query at level 2 "Strategic Human Resources Serv" after selecting Justice -> CMSB.

**Comment by jessicahjwu** [comment]
This issue continues with the Goal Summary report for Justice when I tried filtering to org level 2, page returned as 504 Gateway Time-out. However, results returned when org level is filtered to level 1 only.

**Comment by jessicahjwu** [comment]
This issue continues with the Goal Summary report for Justice when I tried filtering to org level 2, page returned as 504 Gateway Time-out. However, results returned when org level is filtered to level 1 only.

**Comment by jizhaogit** [comment]
Dennis and me did a quick check from both of our side.  neither of us got the 504 error.

**Comment by steffipravasi** [comment]
Filters for Justice Level 2,3,4 for the Goals Summary Page are working fine and no 504 errors received.

**Comment by jessicahjwu** [comment]
I've just tried re-creating the scenario, it still took a bit of time for the result to return but everything worked. No more time-out messages displayed.

**Comment by jizhaogit** [comment]
We haven't made any modifications or optimizations at the code level for issue #1200. Warren helped by increasing the CPU and memory of the database, and it seems that the performance issue caused by the spark is not affecting us for now. We'll continue to monitor the page's loading performance closely. If we encounter similar issues in the future, I suggest we consider rewriting the page to improve performance. Instead of loading all the data, charts, and reports in the controller, we could implement an AJAX approach where users can click on a report icon to fetch it dynamically. This approach would enhance the page's responsiveness and efficiency.
