### ISSUE TITLE
Supervisor is still able to access the completed conversation with former direct reports

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1278]
Scenario: Travis Clark (163102) has moved on to another role since beginning of Feb. However, he is still able to view/ access the past completed conversations that he has had with former direct reports: Jessica Wu and Zehra Pirani LeRoy. 

Business Requirement: Supervisors should not have the access to view past completed conversations with former direct reports. For historical details, please refer to ticket #551.

**Comment by steffipravasi** [comment]
Test data:
1. Goal Setting - Travis Clark, Athena Ren ( Direct report) 
The goal was marked as completed and was displayed in both Trais and Ren' profile since Travis was still the direct supervisor for Ren
- Changed the supervisor for Ren through supervisor override
- Dennis ran the overnight process
- The entry has been removed from Travis' profile
- Conversation can still be seen in Ren's profile
2. Performance Check-In, Goal Setting - Travis Clark, Shawna Wilson (share report)
- The goal was marked as completed and was displayed in both Travis and Shawna' profile since Travis was still the shared supervisor for Shawna
- Removed the shared relationship
- The entry has been removed from Travis' profile
- Conversation can still be seen in Shawna' profile
