### ISSUE TITLE
Troubleshoot dropdown menu in Dev being visible for Review participants

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#201]

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M @freshjwarren The drop down menus did not display correctly again during sprint review #4 for MS Teams participants (including me). It doesn't seem to matter if the content is launched from the openshift environment or KK's local environment, the drop down menus show up as black boxes rather than text for MS Teams participants, even though they appear normal and functional to the person sharing the content. Not sure how to troubleshoot or solve. Thoughts?

**Comment by freshjwarren** [comment]
I recommend that you set up a session to troubleshoot this with Travis,
Kousthubha and one other person with a government workstation. You can
invite me if you think I'll be helpful.

**Comment by Travis-A-Clark** [comment]
Solution: share "desktop" and not just a single window. Verified for our test environment.
