### ISSUE TITLE
Delete button throws SQL exception

### ISSUE THREAD

**Issue by kkapoor-fresh** [bcgov/performance#209]
Trying to delete a conversation using the "Delete" button , throws a "Foreign Key constraint/Referential Integrity" on the Conversation ID in the database.
Seems like the conversation ID in the Conversations table is tied to the conversation ID in the conversations_particpants table. This means I cannot delete a conversation without deleting the corresponding entry in the conversation_participants table.

**Comment by Travis-A-Clark** [comment]
@kkapoor-fresh Has this issue been resolved? Yesterday in both the test and dev environments I received an SQL error when attempting to delete a goal from the current goals page (screen shot below). Not sure if this was just because of the OpenShift issues, or if the delete functionality issue remains. Let me know. Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/70462ab9-ec76-48f2-98f4-0a412a4cb2e2)

**Comment by kkapoor-fresh** [comment]
@Travis-A-Clark  This issue pertains to Delete functionality not working for "conversations". I found this issue when we deployed changes to conversation related features. This was fixed. 

@Kousthubha-M Could you please confirm on the delete functionality regarding for the "Goals" ? I am able to delete goals.

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark @kkapoor-fresh  Even I could delete goals. Are you still facing the issue @Travis-A-Clark ?

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Everything seems fine this morning. I just wanted to double check. If there is no known issue outstanding, I'll close this ticket. Thanks!
