### ISSUE TITLE
As a supervisor, I want to be able to have other employees’ profiles shared with me 

### ISSUE THREAD

**Issue by phoebesolomon** [bcgov/performance#272]
- [x] Design
- [x] Dev
- [x] Deploy

**Comment by phoebesolomon** [comment]
- [ ] Design
- [ ] Dev
- [ ] Deploy

**Comment by phoebesolomon** [comment]
![Supervisor Dashboard - My Employees 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/02a9a03c-69e4-4645-a9a2-e01d2a63b7f4)![Supervisor Dashboard - My Employees 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/f502bbc7-af9f-4e97-b81d-152ea42f5762)![Supervisor Dashboard - My Employees 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/04c8ebf0-66ba-435f-bf45-c600bff16760)![Supervisor Dashboard - My Employees 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/59076def-8bf0-4fbc-94b0-b815d91bd00f)![Supervisor Dashboard - My Employees 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e98cfe99-4a71-4e7d-89b5-062d1987aa59)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon This looks awesome! KK may have some questions for you and I once he gets down to coding, but I think this sets us up really well.

My only thought is that the "Shared With Others" heading in the "Shared with Me" table might be a bit confusing. Since someone shared the profile with you, that must mean that someone else already has access, so this column would always be "Yes". Maybe we could change it so that the column heading is something like "View Shared Status" and instead of Yes/No it was just a "View" link that led to the share info for that employee. Maybe not the right wording, but that idea. Thoughts?

**Comment by phoebesolomon** [comment]
@Travis-A-Clark I agree, are you suggesting that we implement that in the "My Direct Reports" table as well? I think it needs to be consistent

**Comment by Travis-A-Clark** [comment]
@phoebesolomon I wasn't initially thinking that, but it does make sense. Consistency is never a bad thing!

**Comment by phoebesolomon** [comment]
![Supervisor Dashboard - My Employees 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e13bc115-9145-440c-8b28-545e60b34862)![Supervisor Dashboard - My Employees 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/52ce4c81-578c-41f4-8ba2-714bb81d5d9b)![Supervisor Dashboard - My Employees 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/08e29a8d-b1be-43ef-aaa0-a4dda1a09795)![Supervisor Dashboard - My Employees 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/04d2ef7f-9a9a-4ce9-b845-9d522682aa87)![Supervisor Dashboard - My Employees 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/e93b6431-ff2a-47d5-945a-0b3c5da605f5)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark see revisions above

**Comment by Travis-A-Clark** [comment]
Receiving the following error message when loading Supervisor2 profile after sharing employees with Supervisor 2.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c43fe5e8-2c5d-43f5-8b60-a287e7c102ef)
