### ISSUE TITLE
Create user test plan for HR Admins

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#292]
Suggest optimal format to engage with HR admins to get feedback on admin landing page and functionality. One on one, group, etc. Draft recommendation and outline for testing session.

Travis to reach out to HR admins to ask for participation once plan is finalized.

**Comment by deknees** [comment]
Plan and script in [figjam](https://www.figma.com/file/NeaN67fmkt1f4LQzb2ikwS/Performance-Development-Supervisor-Team-Tab-User-Flows-Copy?node-id=0%3A1) ready to take notes during interviews.
Focusing on finding out what current system struggles are, show new design and find out if make sense instead of letting users click around prototype. (wasn't efficient from last experience) 
![Screen Shot 2021-09-17 at 2.29.18 PM.png](https://images.zenhubusercontent.com/6104230965b7a36ff099bd68/a14d4b2a-ea5d-4ade-8686-353fd7488304)

**Comment by Travis-A-Clark** [comment]
This work seems to be well underway. Thanks!
