### ISSUE TITLE
Azure Log-In: I want the log-in process to understand when an employee is "shared" with me

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#392]
Adding the additional use case to the Azure log-in process to make sure that "shared" supervisors are given correct access when they log-in.

**Comment by jp-Telus** [comment]
**Work done**

During the signon process, the program will change check either current authenicated user has employee under him or he has shared profile, then the "supervisor"    is assigned. otherwise, the "supervisor" role is removed if they has in the before .

This enhancement was already pushed to REPO, deployed on both DEV and Test region.

**Comment by Travis-A-Clark** [comment]
Thanks, @jp-Telus ! I'll close the ticket.
