### ISSUE TITLE
As a user, I want consistent navigation throughout the platform

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#435]
See attached for navigation structure for the minimum viable product launch in June. After using the system quite a bit the last few days, I think the attached separation makes the most sense and keeps the content on each page manageable. Let's chat if there are question and then incorporate into all designs.

This assumes we go with the other changes proposed in tickets #431, #433, #434. It also impacts the arrangement of the Sys Admin pages that Dennis is working on. It won't impact his actual work, just the presentation of it.

[https://app.zenhub.com/files/329107952/8b8c94d3-a8bf-48f4-b79b-a01596655b34/download](https://app.zenhub.com/files/329107952/8b8c94d3-a8bf-48f4-b79b-a01596655b34/download)

**Comment by phoebesolomon** [comment]
@Travis-A-Clark all the mockups are completed for this ticket but I don't think it is a good idea to upload them all to this ticket because there are over 30 screens. Maybe just for this ticket, the devs can refer to the Figma instead? Link copied here https://www.figma.com/file/Zsvxg6Q0lbJfl9sEqkWmC0/Perf-Dev?node-id=0%3A1
