### ISSUE TITLE
As a supervisor, I want to receive an email when one of my employees conversations is a week away and when it's past due

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#474]
Additional work and troubleshooting is captured in ticket #803. 

- [ ] Send email and post notification to Performance Platform homepage for a supervisor when an employee's conversation due date is one week away

- [ ] Send email and post notification to Performance Platform homepage for a supervisor when an employee's conversation is overdue (one time only, once current date is later than due date)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

I have added the additional procedure under the current schedule command "command:NotificationProcess" which run every day at 1:00am, to generate the in-app and email messages to the supervisor 
1. when an employee's conversation due date is one week away
2. when an employee's conversation is overdue (one time only, once current date is later than due date)


Note: 
1) the email will only sent based on the highlighted settings, there is no month away due notification will sent per requirement.
2) the supervisor get individual email per employee since they will have difference conversation due date. COuld you please kindly provide 2 sets template for me, something similiar to "CONVERSATION_DUE" and "CONVERSATION_REMINDER" for the supervisor?  Thank you.  

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/1c02f729-faba-4d1d-9c6e-195f92529af1)


I can only test on my local since I have to override the conversation due date to trigger the notification. here are some screenshot for your review: 

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/0c2ecf6a-4c55-4302-a18a-6c085043dc66)

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/cfd0862e-edbf-4895-a4c2-e79c22bb08dc)
I have requested the TEST migration.

**Comment by Travis-A-Clark** [comment]
@jp-Telus Thanks! Is there something similar set up for one month from conversation due date? I'm not sure why I didn't include that in this ticket for supervisors. I know it's there for employees. Sorry for any confusion!

**Comment by Travis-A-Clark** [comment]
@jp-Telus I created two new templates in Dev: SUPV_CONV_REMINDER and SUPV_CONV_DUE. I am hoping we can use the SUPV_CONV_REMINDER in the same way that we use the CONVERSATION_REMINDER for employees where the same message can be sent 1 month and 1 week out from employee due date.

**Comment by steffipravasi** [comment]
The conversation part for supervisor will be tested later as there is not much possibility of changing the conversation due dates. We'll be testing this issue when conversation due dates are near. We can close this ticket for now and track the issue next month.
