### ISSUE TITLE
Putting "www" in front of the URL causes an IP server error

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#671]
performance.gov.bc.ca loads the expected log-in page.

www.performance.gov.bc.ca returns the following error.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f0a1b2e1-5853-41b6-8eef-16b208be224c)

**Comment by kkapoor-fresh** [comment]
@Travis-A-Clark Is it mandatory to use www?  We havent used www in any of the PSA projects(like moodle or Digital journeys) . Mostly all websites like google, netflix etc. use https:// . I believe this was a prefix use in early days of internet and has been much replaced by https:// in the modern days.  Secondly, www uses "http" instead of "https" which is secure protocol. That's the reason we have been have add those SSL certifcates installed to our domain to ensure encryption in flight thus enhancing security. I guess if at all we want to change still use the www, perhaps we could have it redirect to "https" fron within the application logic. @telusdcinco Can you please comment on that.

**Comment by kkapoor-fresh** [comment]
We’ve discussed this as a team and realized that it’s not government standard to use “www” prefixes for internal apps. So the non www DNS record should be good for now.
