### ISSUE TITLE
As a System Admin I want to be able to see a dashboard of employees within any/all business units

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#71]

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - My Organization - Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/1d02eee7-1f75-4d71-8385-6e5dbb7dfff4) ![System Admin Dashboard - My Organization - Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5770bb5a-f31a-4797-a4de-2c3095d53a69)

**Comment by phoebesolomon** [comment]
@telusdcinco this is the ticket for the "My Organization" tab - see mockups attached.

**Comment by Travis-A-Clark** [comment]
In the search/filter functionality at the top, we had talked about having the top line being the org units (as displayed) and then having a multipurpose search function below (currently shows job title and search box). Instead, have a dropdown list of other table properties (i.e. employee ID, classification, department ID, etc) and then the text box to enter the search criteria you are looking for. Basically, use this as a catch all for all over our table elements that someone might use to try to narrow a search.

**Comment by phoebesolomon** [comment]
![Ticket 71 - Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/0e6ef93d-b0cc-466c-a1e1-53438627d256)

![Ticket 71 - Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/b3d092ae-b072-467b-955c-6eef2a9aa602)

![Ticket 71 - Part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/60553c09-2ed4-4cbb-8af7-eb124b87ac17)

**Comment by phoebesolomon** [comment]
Edit Goal Bank Mockups:

![Edit Goal Bank 1.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/fbd13abb-9026-4996-bcbf-23812343b3f4)

![Edit Goal Bank 2.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/2fd47fd8-ad54-4441-8b97-cc4afced8050)

![Edit Goal Bank 3.png](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/4fc759c6-702c-4ea4-b1b4-328425148002)

![Edit Goal Bank 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/268bdf3e-ef9a-40f2-9efe-344d250d6dd6)

**Comment by telusdcinco** [comment]
Latest version currently deployed.

Pending work...  
- Content needs to be update/adjusted to display required columns/content
- Complete the search function  for specific criteria.
- Fix issue with filter's Organization value being reset to All after clicking Search

**Comment by telusdcinco** [comment]
Deployed to Dev.

Pending...
- Content needs to be update/adjusted to display required columns/content

**Comment by telusdcinco** [comment]
Modified filter version deployed to Dev.  
- Only available to HR Admin.
- HR/Sys Admin roles permission created and deployed to Dev.
- Use hradmin1@example.com,... hradmin2..., & hradmin3... for HR Admin access.

**Comment by jchow11** [comment]
**Description**
A dashboard of employees within all/any business units. 
System Administrator > Employee List > Current Employees
System Administrator > Employee List > Past Employees

**Acceptance Criteria**
-Only available to Sys Admin users
-Ability to filter by 5 "organization levels" as searchable dropdown menus
-Ability to filter by Employee ID, Classification, Department ID as a single searchable dropdown menu
-Ability to search by name or keyword
-Results displayed with Employee Name, Job Classification, and Organization Level(s)
-Past employee section shows all the same functions PLUS ability to search and display "Inactive Since" date

**Test Plan**
![Screen Shot 2022-04-22 at 1.09.10 PM.png](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/c93d09c8-6ab7-4bed-a6b1-c6744de9d8a2)

**Comment by Travis-A-Clark** [comment]
@jchow11 I think the test script and format looks good. I think this will work well for tickets moving forward. Now that I think more about the flow of the tickets across the board, I agree with your initial instinct to put testing after my review since I may ask for alterations and I don't want to waste your time testing something that might change.

For this particular ticket, I am going to move it back into In Progress since Dennis is still incorporating updated org hierarchy formatting and functionality.

**Comment by telusdcinco** [comment]
Testing in progress with completed Access/Permission Admin page.

**Comment by telusdcinco** [comment]
Deployed latest to Dev for review/testing.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Are we able to make the relevant areas of the results table clickable so that the Sys Admin can access the employee profile, see their shared / excused status, etc?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/27460981-5d8b-48bf-b42e-855617fe79dd)

The links should mirror the MyTeam experience:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/411c45b1-e0d0-49e8-ab02-be261242f22a)

**Comment by telusdcinco** [comment]
Mirroring the links to MyTeam is in progress.

**Comment by Travis-A-Clark** [comment]
Moving remaining work to ticket #691.
