### ISSUE TITLE
As Sys Admin, create a facility to enable/disable logins for specific ministries for future roll outs.

### ISSUE THREAD

**Issue by telusdcinco** [bcgov/performance#712]
As Sys Admin, create a facility to enable/disable logins for specific ministries for future roll outs.

**Comment by jp-Telus** [comment]
New page added for specify which organization's users allow to  login, get the In-app message and email notification.

Menu > System Administration > System Security > Access Oragnizations

Note: Ready in DEV region for testing

Migration Notes
> php artisan migrate
> php artisan db:seed --class=AccessOrganizationsSeeder

**Comment by steffipravasi** [comment]
@Travis-A-Clark If the user selects multiple organizations through the checkbox and changes the access, then should it update on selected organizations? Right now, although multiple organizations are selected, only the organization where the Change button is clicked updates.

**Comment by steffipravasi** [comment]
@Travis-A-Clark I have some follow-up questions:
1) Does the Allow In-App Message means conversations/notifications?
2) "Allow Email Message" are we testing this feature through emails?
3) Should the "Reset Selected"  option change to default settings or to the setting before the changes were made.

**Comment by Travis-A-Clark** [comment]
@steffipravasi I am going to move this into the PO Review pipeline because I am really the only Sys Admin at the moment so it makes sense for me to go through this testing. In answer to your questions:

1. Allow in-app message means notifications on the employee homepage
2. Yes, we will have to work with James who has test accounts set up through Outlook Exchange
3. I think we can remove the "Reset Selected" as there are already options to enable / disable
4. No, the employees are not notified when these changes are made. The communications are handled separately.

**Comment by Travis-A-Clark** [comment]
@jp-Telus I think we will need to set up 15 minutes to test this together. Having issues with logging in now that it's pushed to the Test environment. I am also not having success blocking in-app notifications with the option provided. I don't want to move this into Production until we do a fair bit more testing.

**Comment by jp-Telus** [comment]
@Travis-A-Clark 
Thank you for testing result. 
1. Yes, I found a bug in the program, I checked the "Allow In-App Message" value instead of the "Allow Login" value in the "Access Organization" setting page. 
2. Sorry for the confusion, I didn't have the same login organization access chcking in the regular Laravel login, (Sorry, :( I was mixed up with PECSF ). Now, I have added it back,

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Deployed the changes on the DEV and done some test cases by using the Laravel UI login (using login as adminsitrator page):

```
User                           Organziation                                 Result
Tony.Loughran@gov.bc.ca        'Advanced Education and Skills Training'      Login - Failed  
SSAMPSON@royalbcmuseum.bc.ca   'Royal BC Museum'                             Login - OK      
Tess.Hawkins@gov.bc.ca         'Social Development and Poverty Reduction'    Login - OK      
Heather.Davey@gov.bc.ca        'BC Public Service Agency'                    Login - OK      
Amy.Lee@gov.bc.ca              'BC Public Service Agency'                    Login - OK      
ilyana.rooke@pensionsbc.ca     'BC Pension Corp'                             Login - Failed          
```

Work as expected, currently, there are only 3 organizations wiith 'Allow Access' option is 'ON' in DEV region.

Please kindly confirm the TEST migration. Thank you.

**Comment by Travis-A-Clark** [comment]
@jp-Telus Yes, please push to Test so that I can work through a few different scenarios there. Thanks!

**Comment by Travis-A-Clark** [comment]
@jp-Telus Please see below for a couple of notes. Happy to chat further. Thanks!

1) As a Sys Admin, if I create a goal in the goal bank and assign it to an org that is not allowed to receive notifications, I get a 500 error. The goal is added correctly and displayed correctly, but I am assuming the system is trying to run the notification script and is being blocked resulting in the error message. Can we have it do a check before running the script and prevent it from going to the error?
<br>

2) Once the in-app messages are turned on, it displays all historical messages created before the permission was allowed. Perhaps this could also be solved by having it run a check first before trying to generate the notification. I think it should only display notifications generated after the time the permission is enabled.
<br>

3) Even with all three permissions enabled, the error 500 messages is still displayed. I created a goal for a group in Citizen Services with all permissions enabled. I received the error 500. The goal was created properly. I didn't receive an Outlook notification. I thought I was hardcoded as the only recipient. Any chance an actual email went out?

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Issues 1 & 3: I believe the 500 error is happened in TEST region because of the dependency change in #636 which is not yet in TEST region.

Issue 2: Actually, In-App message option is only apply to control the "conversation overdue generation" (batch process run on every day). there is no control on the online page. Should I add this control (checking before creating the the In-App message on every online page?   Please advise.

Thank you.

**Comment by Travis-A-Clark** [comment]
Issue 2: yes please go ahead and add the control to check before creating in-app messages. Thanks!

**Comment by jp-Telus** [comment]
The following business areas are improved to have checking before create Home Page In-App message based on the In-App Message option under security access control page, this mean the In-App message will only generated when the employee under the organization with the In App Message turn on only

1. Goal (GoalController)
2. Goal Bank HRADMIN/SYSADMIN pages (GoalBankController)
3. My Team (MyTeamController)
4. Share Employee (EmployeeShareController)
5. Conversatioin (ConversationController)
6. Daily Schedule Process (command called NotificationProcess run at 1:00am PST)

The notification log page also improved to show the In-App message detail and the receipent.

Note: migrated to TEST region.

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test
User: Sys Admin
The specific ministries can be disabled/enabled for login, allow in-app, allow email. Emails are received when access is enabled.
