### ISSUE TITLE
My Goals > Current Goals - Design 2.0

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#743]
**Description:** 

Changing the format of the My Goals > My Current Goals area to be consistent with the rest of the My Goals pages. Currently they are cards, we would like them to be displayed in tables which can be sorted, and contain more information within the space of the page.

 

**User Story:** 

As a BC public service employee, I want to see my Current Goals in the same format as the rest of the My Goals space so that I can easily find, sort, and view goals.

 

**Acceptance Criteria (this ticket is “done” if...):** 

- Sortable columns to include: Title, Type, Tags, Start Date, End Date, Status, Shared With (for supervisors only).
- Filters/search at top to include: Title, Type, Tags, Start Date, End Date

**Designs**
Employee
![My Goals _ Current Goals.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/8332a8a2-6dc0-43ba-b593-2583507022ea)

Supervisor
![My Goals _ Current Goals (Supervisor).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/9b340d68-6783-4878-81f2-b7769a296825)

**Comment by Travis-A-Clark** [comment]
@jchow11 This is looking good! Just two requests for the search/filter area:

1) Please move Tags to the third spot so that it's in the same sequence as the table columns below
2) I think we need separate search options for Start Date and End Date

**Comment by jchow11** [comment]
@Travis-A-Clark updated the designs! Let me know if that works.

**Comment by jizhaogit** [comment]
changes are deployed in the test ENV. 

A question. since it is the list for "current" goals,  should we still need the column "status"?  i currently removed it but if need we can add it back.

**Comment by jizhaogit** [comment]
1.  added back the status field in the list
2. increased row per page from 4 to 10 as requested.

**Comment by jizhaogit** [comment]
checked with shared with logic.  if a user is a simple employee, he should not be able to see the "shared with" selection.  so this bug is to hide "shared with" column from a simple employee's table.

**Comment by SSubashree26** [comment]
@jizhaogit 

For normal employees, because the "Shared with" option is not displayed anymore, the alignment of the "Status" column heading and  their corresponding values are not looking good.

![image.png](https://images.zenhubusercontent.com/63892df90d58261296a2b5c0/213a1972-b347-4e4b-9b9a-b5e0a1e4555e)

Can you please have a look at it?

**Comment by SSubashree26** [comment]
@jizhaogit 

Hi Ji, I retested this again and I don't see a difference in the alignment. I even tried clearing the cache and verifying it in different browsers, however, had no luck. Can you please have a look at it again?

**Comment by jizhaogit** [comment]
the alignment change has been pushed to test.

**Comment by SSubashree26** [comment]
Completed validating Observation 1 and Observation 2 in the testing environment and they are working fine.

Screen Recording:
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23743/Performance%20743.mov?csf=1&web=1&e=bqGMb6

**Comment by SSubashree26** [comment]
@jizhaogit 

Hi Ji, I am still able to recreate observation 3. Can you please have a look at it?

Observation 3:
In Firefox, after making changes to the "Shared With" field, if we click on the left side, it automatically clicks Cancel in the popup displayed and we happen to lose the selections/changes made to the "Shared with" field. Not sure if this is because of the popup position in my screen
https://bcgov.sharepoint.com/✌️/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23743/Firefox%20-%20Values%20not%20getting%20saved%20.mov?csf=1&web=1&e=gZnrrh

**Comment by SSubashree26** [comment]
Thank you for confirming @jizhaogit. Moving this story to "PO Review" column
