### ISSUE TITLE
As an employee, when I click a home page notification I want to be taken to the specific item referenced, not just the general page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#751]
Current situation: an employee receives a notification on their home page that says a new goal has been added to their goal bank. The high level details of the goal are listed. Clicking on the notification takes the employee to the general Goal Bank tab but does not open or highlight in any way the goal that has been added. This is also true for notifications about conversation creation, sign-off, and disagreement. The user is taken to the Open Conversations tab, but the specific conversation is not loaded.

Desired outcome: clicking on a notification navigates the user to the correct tab and also launches the specific item.

**Comment by jp-Telus** [comment]
Since the detail pages are displayed in the "Modal" page on the original transactions, so additional logic and coding has added to handle the Modal box popped when click on the "view" from Home page, 3 areas were updated for open when passing the related_id:   

1. Conversation (ConversationController)
2. Goal Bank (GoalController)
3. Shared Profile (DashboardController)

**Comment by steffipravasi** [comment]
Test status: Pass
Env: Test
