### ISSUE TITLE
Update display and messaging for excused status

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#795]
- [x] Update the message on the employee profile to say "Employee is currently excused and their conversation deadline is paused."

Change next conversation due date to "Paused" in the following places when excused = "Yes" 
- [x] My Team > Team Members
- [x] HR Admin > My Organization
- [x] Sys Admin > Current Employees

**Comment by steffipravasi** [comment]
Test status: Fail
HR Admin -> My Organization
The excused status is expected to be 'Auto' instead of Yes
![Screen Shot 2022-10-18 at 3.21.15 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d1a515da-87ec-479c-bfc4-a96cb4732576)

Update the message on the employee profile to say "Employee is currently excused and their conversation deadline is paused." : **_Pass_**
![Screen Shot 2022-10-18 at 3.22.50 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e813f64a-4142-42ce-add0-a2fb6a853d44)

My Team > Team Members : **_Pass_**
![Screen Shot 2022-10-18 at 3.24.26 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/42fd1cbe-78e2-488d-91c1-70b842f6a285)

**Comment by steffipravasi** [comment]
Test status: Pass
The excused status is changed to 'Auto' for HR admin -> My Org
![Screen Shot 2022-10-19 at 1.31.01 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e62c64ea-e358-4582-96c5-36d16307eb84)

**Comment by Travis-A-Clark** [comment]
PO approved
