### ISSUE TITLE
As a Sys Admin, I want to use DeptID instead of 5 org levels to map goals and HR admin access

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#796]
**Current Situation**

Goals assigned through the goal bank and access assigned to HR Admin are based on mapping to the 5 org levels in the PDP to that goal or individual. For example, pushing a goal to Public Service Agency > People and Organizational Development > Corporate Workforce Strategies. The issue is that if there is any change to the text in any of the 5 org levels, the mapping to the goal or admin access breaks. If the example organization decided to change their name to Corporate Workplace Strategies, the goal previously assigned to them would disappear. We are starting to see this happen in pilot groups as they update the names of their business units over time.

**Desired Situation**

The 5 org levels will still be used to navigate and display information in the PDP. However, the mapping of goal bank goals and HR admin access will be to the numerical DeptIDs rather than the text based 5 org levels. The DeptID should be more stable and result in far fewer issues.

**Initial Plan of Action**

- [x] Create new table for DeptIDs
- [x] Migrate the HR Admin > My Org table to the new table and test

We can create smaller tickets for individual work as required moving forward.

**Comment by telusdcinco** [comment]
Started working on this ticket.  Backend views to support the new data retrieval completed in #838, but is currently only in my local.  The changes will be pushed to Dev/Test together as needed.

**Comment by telusdcinco** [comment]
Reverted changes from Test, to troubleshoot production issue when adding orgs to existing goals.

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
Dev review has resulted in overnight process to fail for generating a new org table with deptid based on the employee demographics table (from ODS).
The failure is due to the fact the employees have current deptid that are tied to multiple 5 org level configuration as shown below, for example.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/2b5f9ac1-2fdb-426e-871b-fc8c27c2b3f5)

This revelation will require additional discussion, for  the true source of the deptid-5 org level relationship.  The assumption was that there will only have one 5 org level config for each dept id.

**Comment by telusdcinco** [comment]
Related changes being applied for #785

**Comment by telusdcinco** [comment]
Overnight process to pull organizational/department data from ODS completed.   The process also takes care of the "unallocated" and repeating levels.

Pending changes on the My Organization page for the new filter and search functions.

**Comment by telusdcinco** [comment]
@jizhaogit  Please review changes.  Thanks.

**Comment by jizhaogit** [comment]
@telusdcinco thanks Dennis, please go ahead for the test migration.

**Comment by telusdcinco** [comment]
@jizhaogit  Please review changes (2nd batch).

**Comment by telusdcinco** [comment]
New changes due to ODS org re-branching scenario.

- Overnight process to pull ODS Dept Org data will recreate the details from scratch.  Updating previously download data is not advisable and may lead to duplicated rows which may break the Org Tree Build.
- Org Tree Build have been modified to rebuild the tree from scratch using a temp table.  This should allow for the org dropdowns to function even when the process is running.  Once the tree is built in the the temp table, it will be transferred to the actual table used in the dropdowns.  It only takes less than a second to transfer which should limit the org unavailability to a fraction of a second just after midnight (as scheduled).

These changes needs to be pushed to Training for manually running the overnight processes.
