### ISSUE TITLE
Conversation due email not received for team members and supervisor

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#803]
Users have not received emails for one month due conversation whereas in-app notifications are received.
Env: Test

**Comment by steffipravasi** [comment]
Emails received when triggered manually by Dennis. 
Issue: typo in the command name
![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/c2d5c33b-cac8-473b-9e26-58c788fc5175)

**Comment by telusdcinco** [comment]
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/d511a89f-4ec6-4929-99c0-f7f88ed223c8)

**Comment by telusdcinco** [comment]
Process completed in Test.

![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/61838163-e96e-4617-9ea0-4228e36c8dbb)

**Comment by jp-Telus** [comment]
Oct 4, 2022, added a function to capture the program output but there is no In-app and email created at designated schedule time. Then I run it manually at 8:00am on command prompt, both In-App and Email were created. Still working on why not working in schedule command.

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/04dc23de-2596-4a7d-bda6-03bba010d91f)

On the other hand, there are new chnages required for deteremine the conversation due date and excused status:
1. To use the field employee_demo_jr.next_conversation_date instead of calculation
2. To use the field employee_demo_jr.due_date_paused for determine whether te In-App and Message will be generated.

The program was updated per new changes requests and also fixed a couple of minor issues.

**Comment by jp-Telus** [comment]
Finally, we knew that the schedule job were execute on the Openshift Cronjob's Pod instead of the PSP Application's Pod. we have encountered 2 issues when the same command was exceuted in the Openshift Cronjob's Pod but not running on the application's Pod:

1. Permssion denied on the laravel.log 
2. Exception encountered when trying to send out email (unexpectedValeuException), unfortunately, we don't have a log to have the detail of the issue. 

Kunal is looking into that there may have difference configuration or setting between those Pods.

**Comment by jp-Telus** [comment]
Warren and Kunal fixed the permission issue by sharing the storage folder between POD on the DEV and TEST regions, after that 2:30am schedule notification process ran successfully and email sent out to the pre-defined recepient on the env setting.

Same fix will apply on Production on Oct 28, 2022 5:00pm


Thank you.

**Comment by steffipravasi** [comment]
Issue received. Automated notifications for conversation due are sent out at 2:30am PT everyday.
![Screen Shot 2022-11-01 at 9.57.31 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/623d399e-8743-4c5b-ab2b-2a90cdbaf06f)

**Comment by Travis-A-Clark** [comment]
@steffipravasi One thing I noticed in the DEV environment (where I still receive the auto emails) is that not all of the next conversation due dates line up with the notification being sent. Reminders are meant to go out one month before, one week before, and when the due date passes. I have reminders this morning with due dates of Nov 19, Nov 21, Dec 2, etc. Is this also the case in TEST?
