### ISSUE TITLE
Missing comments in conversations

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#804]
When we transitioned to the updated conversation templates, some comments were not transferred and displayed correctly. Need to map previous data, and data currently in production, to a single source of truth and display it consistently in the app.

**Comment by steffipravasi** [comment]
@Travis-A-Clark I have tested some of the users with previously closed conversation and can see some old comments there. Dennis gave me few users with previously closed convo dates but since the previously closed conversations does not have much content in the comments for testing, we don't have a good amount of users and data to test. Please let me know how should we proceed with this ticket.
