### ISSUE TITLE
As a Sys Admin I would like a detailed activity log / audit for the app

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#828]
The PDP needs an audit log that the Sys Admin can access to view changes to app content. There is an existing function in MyPerformance that does this (see example screenshots below). We need this for a number of reasons including the fact it could help us troubleshoot what is happening to disappearing content from conversation comments and help us restore this content if required.

Search interface:
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8a6f1cf2-8ff6-4f22-bc8b-73a40e63c833)
<br>

Example results returned:
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/469b4f14-dce9-4eae-91e2-3d88b161bb8d)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Luckily, the laravel package for auditing the model data changes has been installed by KK to track the Goal record since lasy year. I have enable the same function for the "Conversation" and "Conversation Participants", and also built a new page called "Auditing" for you to verify the data online. 

Menu: System Administration > Auditing

DEV and TEST deployment were done and please kindly verify this new page and auditing functions.

Thanks

 The new "Auditing" page

**Comment by Travis-A-Clark** [comment]
@jp-Telus This looks great! I think it covers all the basic elements and it seems accurate.

One question: any chance this can also track the comments in the Goals area?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/4a458d9f-99fd-4ccf-9077-5912058ddec9)
