### ISSUE TITLE
Missing comments in conversation

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#829]
We have bugs reported that the comments are missing from the conversation. 

**Finding1 details:**
Environment: Test
User: Employee: Chad Hoskins, Supervisor: Travis Clark
Browser: Travis - Edge, Chad - Safari
Conversation type - Career Development

Travis added his comments and closed the modal by clicking Ok
Chad added his comments and closed the modal by clicking Ok
When Chad opens the conversation back, his comments are disappeared.

Example can be viewed in the recording below
Recording - https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/MissingComments(1).mov?csf=1&web=1&e=YNmeaM

-------

I added details for two cases occurring in PROD to ticket #830 if that is at all helpful.
Test data can be recorded in [Document](https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/doc2.aspx?action=editNew&sourcedoc=%7Bd0915837-5ff3-4fdb-9729-20c54d547848%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1667584999066&web=1&cid=b9605be7-dd57-42c4-8d9b-28cb06d5aba9)

**Comment by steffipravasi** [comment]
@Travis-A-Clark This seems to be a browser cache issue confirmed by @jizhaogit 
We followed these steps for testing:
    Environment: Test 
    User: Employee: Olurotimi Famodile, Supervisor: Travis Clark 
    Browser: Travis - Safari, Olurotimi - Firefox 
    Conversation type - Career Development 

Steps:  

    

-     Travis added his comments and closed the modal by clicking Ok 
-     Olurotimi added his comments and closed the modal by clicking Ok 
-     When conversation is opened both the sides comments are added. 
-     Travis opens the modal again and make changes and at the same time Olurotimi opens the modal and made changes. When closed together, the updates are not stored. Me and Ji also tried opening the conversation for Travis only and making changes, save and closing the modal. When opened again the changes are not saved.

    **When page is refreshed and tried all the above steps again, then its working fine and  updates are saved.**

**Comment by Travis-A-Clark** [comment]
@steffipravasi @jizhaogit That makes a ton of sense. I've been asking about potential cache issues on a number of tickets. I also just created ticket #832 to document the issue with accessing the conversations through the homepage notifications. Depending on the order that you click on different conversations during the same session, you see different comments. This strikes me as a cache issue as well. Let me know how things progress!

**Comment by jizhaogit** [comment]
added "stop browser cache" meta request in the page template

<meta http-equiv='cache-control' content='no-cache'>
<meta http-equiv='expires' content='0'>
<meta http-equiv='pragma' content='no-cache'>

**Comment by steffipravasi** [comment]
@jizhaogit @Travis-A-Clark 
Issue still occurring on Test env
Users: Team member: Emily Hannah, Sup: Julia Norman
Browser: Emily - Firefox, Julia - Safari
New conversation for Career Development created, added comments and closed at the same time. When opened again, none of the comments were saved.
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/MissingComments2.mov?csf=1&web=1&e=TUENeD

**Comment by jizhaogit** [comment]
there are some conflict for the bulk saving feature.  now i re-invited separate comment saving feature to avoid this conflict.

**Comment by steffipravasi** [comment]
Test browser: Safari, Chrome, Edge, Firefox
User: Shannon Baskerville, Cory Scott
- After the new fix with the Save button for each comment section, the entered comments are not lost from either side. 
- Comments restored in Open and Closed conversations.
- The comments are stored when conversation modal is filled out one after other or at one time from both the ends(Supervisor and team member)
- If comments are not saved, then they are stored with the Auto save option

**Comment by Travis-A-Clark** [comment]
Three things I am hoping we can do:

1) I really like how there is a "Comments saved" notification when you use the Save button. Is it possible to have that same message displayed in all areas where comments have been saved by the auto-save function? I know there is the pop-up that says all comments have been saved, but it would be great if the specific comment areas that have been saved were also highlighted with the red notification.

2) Change the auto-save pop-up message from "Your comments have been auto saved" to "You have been inactive for more than 15 minutes. Your comments have been automatically saved."

3) Now that we have the individual save buttons back again, we need to change the logic and message that happens when you try to close the window. I think it should be like the create new goals modal. Change the message and logic to "If you continue you will lose any unsaved information".

**Comment by jizhaogit** [comment]
the 3 requests are ready for testing

**Comment by steffipravasi** [comment]
@jizhaogit 
1) **Test status: Fail**
We have got some issues with highlighting the comment areas that have been saved. 
- Not all the sections are being highlighting when added comments to all the sections.
  Step: Created a Goal Setting conversation, and added comments to both the sections (Didn't click the Save button for either of the section). When auto saved, only the top section is highlighted.
![Screen Shot 2022-11-27 at 2.13.37 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f5d5fa55-da26-4d79-b86d-793617fd0e39)

- In the example below, didn't add comment to the Action Item section, but it still got highlighted after Auto saving.
![Screen Shot 2022-11-27 at 1.56.18 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e9ed2f78-ccad-48b4-ad06-0d4309ca7233)
![Screen Shot 2022-11-27 at 2.42.37 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/d76a8f26-0bf8-49be-b656-047d52424406)
 -----------------------------------------------
2) Test status: **Pass**
The message for auto save has been changed to "You have been inactive for more than 15 minutes. Your comments have been automatically saved."

3) Test status: **Pass**
The logic and message for closing the conversation has been changed to "If you continue you will lose any unsaved information"
![Screen Shot 2022-11-27 at 2.56.14 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/0729745e-7980-40b0-9b9e-123181b6bed4)
Only the Saved comments are stored when the conversation is closed. Any unsaved changes will be lost if clicked Okay in the dialog box.

**Comment by steffipravasi** [comment]
Testing blocked with #865. 
The auto save happens within the next few mins of opening the conversation and happens more often which makes the testing comments difficult.

**Comment by steffipravasi** [comment]
1) Test status: Fail
Not all the comments saved in the Auto save feature are highlighted
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/CommentsNotHighlighted.mov?csf=1&web=1&e=GE210T
Steps: 
- Add comments to all the sections and do not click the Save button for any comment
- Leave for 15 mins
- With auto save, only the last comment section is. highlighted.
Expected results: All the comments sections must be highlighted.

**Comment by jizhaogit** [comment]
Hi @steffipravasi this behavior is due to the ckeditor input area focus.  Please try with all the comments dose not be activiated (that means while you wait for the time, make it sure that is no "save" button appears)

**Comment by steffipravasi** [comment]
@Travis-A-Clark 
Me and Ji have tested the comments part and most of the functions are running fine. 
We have changed the auto save time from 15 mins to 1 min on test environment for testing purpose only. 
3 scenarios we need to know for the auto save and discuss if we find a way to fix them:
1) When comments are entered and user clicks somewhere outside the browser, the focus is no more on the page. Due to which the section where last comment was entered is not highlighted and shows the Save button instead. 
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/NoFocusOnPage.mov?csf=1&web=1&e=qoYR3J

2) If some comments are added to the sections and after auto save the section is highlighted, when user clicks in to add some text, the Save button won't populate. Save button is displayed only after clicking elsewhere on the screen and then clicking back in the section.
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/SaveButtonNotAppering.mov?csf=1&web=1&e=GifRcB

3) When multiple auto save occurs after 30-45 mins of inactivity (3times), the sections which were supposed to be highlighted won't be seen. This is due to multiple cycles of auto save running which overwrites the results of the first cycle. 
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/MultipleAutoSaveDoesNotHighlight.mov?csf=1&web=1&e=Kjc6uz

**Comment by Travis-A-Clark** [comment]
Thanks for this! 

1. I think that scenario 1 is okay because the comments are actually being saved, so they aren't in danger of losing anything. At worst, they will come back and click the Save button again since it shows up. Not a big deal.
2. This is a bit more troubling because the user does not see the Save button and may end up losing information if they add text and then close the window. 
3. I think this is also okay for now because they aren't in danger of losing any content. They may just not see the right highlighted notification.

If there is a quick way to fix scenario 2, please do. Don't worry about 1 and 3 at this point.

Also, when we push to production, let's increase the auto-save time to 20 minutes. Thanks!

**Comment by Travis-A-Clark** [comment]
Thanks for this! 

1. I think that scenario 1 is okay because the comments are actually being saved, so they aren't in danger of losing anything. At worst, they will come back and click the Save button again since it shows up. Not a big deal.
2. This is a bit more troubling because the user does not see the Save button and may end up losing information if they add text and then close the window. 
3. I think this is also okay for now because they aren't in danger of losing any content. They may just not see the right highlighted notification.

If there is a quick way to fix scenario 2, please do. Don't worry about 1 and 3 at this point.

Also, when we push to production, let's increase the auto-save time to 20 minutes. Thanks!

**Comment by Travis-A-Clark** [comment]
@jizhaogit For now, let's just increase the auto-save time to 20 minutes globally and then I think we can push this to production.

**Comment by jizhaogit** [comment]
@Travis-A-Clark  a new deployment is in test ENV for fixing option #2. after the alter box trigged, and user keep adding content, the save button will now display once them input anything.  

the auto-save time is still in 1 minutes for us to test. once get approved i will update it to 20 minutes as requested.

**Comment by steffipravasi** [comment]
@jizhaogit The point 2 issue is now fixed on test. 
The Save button appears when comments saved section highlighted.
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Test%20cases/SaveButtonFixed.mov?csf=1&web=1&e=4VjQfR

Please change the auto save time to 20 mins.

**Comment by jizhaogit** [comment]
1) #2 issue is fixed.
2) auto-save time changed to every 20 minutes.

**Comment by steffipravasi** [comment]
@Travis-A-Clark @jizhaogit 
I have noticed that the auto save time is logged from the time when the conversation is opened and not from when the user is being inactive.

**Comment by Travis-A-Clark** [comment]
As discussed at the scrum this morning, let's update so that the timer for auto-save resets whenever someone clicks "save" on any of the focus items.

We can keep the timer at 20 minutes.

Let's update the message on autosave to say: "You have not saved your work in 20 minutes so the PDP has auto-saved to make sure you don't lose any information."

**Comment by jizhaogit** [comment]
time re-calculate and new message are updated in test.

**Comment by SSubashree26** [comment]
Completed validating this bug in the testing environment and it is working fine. However, had an observation of comments not getting saved, when the popup blocker is enabled in a browser. Ji and I would be testing it again tomorrow, and close the bug post validation.

Screen recordings - https://bcgov.sharepoint.com/:u:/r/teams/02915/Shared%20Documents/General/Testing/Testing%20screenshots/Performance%23829.zip?csf=1&web=1&e=jbgaHP

**Comment by SSubashree26** [comment]
Retested it today by enabling the popup blockers and the comments are getting saved. Therefore moving it to PO Review

**Comment by jizhaogit** [comment]
time clock is set to 20 minutes as its ready for final verification.
