### ISSUE TITLE
Share status in PROD environment is not displayed correctly

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#834]
**After the deployment on Nov 4, 2022 the following issues have appeared in the PROD environment:**

- My Team: supervisor received Ajax error when loading the page; after clicking "OK" the page finishes loading but shared employees are not displayed.

- HR Admin > My Organization: no employees are shown as shared in the table.

- Sys Admin > Employee List: no employees shown as shared in the table

- Sys Admin > Shared Employees > Manage Existing: the records are there but many of the columns are blank (see screenshot below). This still displays correctly for HR Admin, but not Sys Admin.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/33e059fa-164b-4745-9e0f-0968b852fcb3)

**Areas where the shared function still appears to be working as intended:**

- All Employees > Home Page: shared with at top of page still displays correctly

- Supervisor > My Goals: shared employees still appear in all goal card drop downs and in the goal bank area

- Supervisor > My Conversations: shared employees still appear as participants when setting up conversations

- HR Admin > Shared Employees > Manage Existing: all the data still appears to be here.

**Comment by telusdcinco** [comment]
@Travis-A-Clark 
Item #1:  A few #806  fix on the My Team page was overwritten by yesterday's migration causing the ajax error.  The $806 change is now reinstated in prod.
Item #2:  Querying backend indicates shares are included.  Let's confirm on Monday morning. 
Item #3:  SysAdmin Employee List do show a few shared flags.   Let's confirm on Monday morning. 
Item #4:  There was no change migrated impacting SysAdmin Manage Existing Shares.  It seems some rows without corresponding employee_demo counterparts are being displayed, causing the blank Employee ID, Name, Classification, Org columns, etc.

**Comment by telusdcinco** [comment]
@Travis-A-Clark As discussed, I've pushed the fix for Next Conversation Due Date calculation to Dev & Test.
Additional trigger added to save a new row in the employee_demo_jr table for cases where the conversation is updated resulting in a new Next Conversation Due Date.
This fix will trigger for any user whose Last calculated Next Conversation Due Date does not match the current calculated one.  In essence, this can be the auto-correct for conversation due dates on a daily basis.
The new row inserted will be exactly as the last entry with he exception of the incremental counter id number and the new Next Conversation Date.
