### ISSUE TITLE
As a System Admin I want to be able to assign different user permissions (HR Admin, Contact Centre Employee, etc) by employee ID

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#84]
This is part of Administrative Functions tab. Similar to HR Functions tab. Need to create an "permissions" or "group assignment" option that allows Sys Admin to search for and select any employee and change their access permissions.

**Comment by phoebesolomon** [comment]
![System Admin Dashboard - Functions Landing Page.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/5419ed64-825b-4c6a-83cf-02d8fd10d22d) ![System Admin Dashboard - Assign Employees 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/06ed29d5-39cc-4c7d-91bb-1c5b35ec7c10) ![System Admin Dashboard - Assign Employees 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3b5e99a1-35ec-491d-821b-51981ad5a5a8) ![System Admin Dashboard - Assign Employees 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/3ae137ff-c39a-4610-a4d8-5e7a457a799e) ![System Admin Dashboard - Assign Employees 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/559daa57-f3ba-4a33-a41b-144788e6322b) ![System Admin Dashboard - Assign Employees 5.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a1cc4351-bd11-4d9e-bda0-7b1554b0db76) ![System Admin Dashboard - Assign Employees 6.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/12b0a4f9-1b61-4f57-9129-4ce0d69e67a5) ![System Admin Dashboard - Assign Employees 7.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/a9606368-fc27-4c86-abdb-82bcd0e9fc23)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon An additional layer to this: if I select a user and assign them the HR Admin access, I will then want to indicate which organizations they are responsible for. Basically we will have to have an org selection process similar to the employee selection process so that I can select "Travis Clark" as the employee and then select "Ministry of Transportation and Infrastructure" and "Ministry of Health" as the orgs that Travis has access to (for example). Does that make sense?
