### ISSUE TITLE
As an employee, I want to share my goal with anyone I choose

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#860]
Currently, we have the function for a supervisor to share a goal with any of their direct reports:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/6ed2329b-4ec9-4eb0-bba8-0d7e4bc36389)
<br>

### Step 1: make available to all employees

Let's expand this function to all employees so that everyone, not just supervisors, see the "Shared with" dropdown option on their goals. 

### Step 2: update Shared With dropdown

Let's also expand the dropdown list to be a general directory searchable and multi-selectable like in the My Team > Share employee modal.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/da5eb817-1cd2-4faa-8752-101ea04e933e)

### Step 3: update My Goals heading

Change the "My Supervisor's Goals" heading to "Goals Shared with Me".
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/765ae6e1-7d3b-4750-aad1-05c24cd39a93)

**Comment by jizhaogit** [comment]
1. Is it possible to remove the cross button when there is no employee shared?
fixed

2. Can we change the background color of the tags to the site theme color or any lighter shade theme color?
fixed

3. Change the name of the header to "Goals Shared with Me"
fixed

4. Can we make the shared with list searchable by employee id? I typed the employee if 000086 but see the error as No results found. Issue also persist in the Shared column for team members
**We need more time to find a way for get this requirement**

5. This issue is for user who is not a supervisor (User: Dona Stapley )
fixed

6. Can we display the users separately, so that one employee can be removed if we want? Right now the goal is shared with multiple employees. If I want to remove Employee 3 from the list, it is not possible. I'll have to remove all of them.
fixed

**Comment by steffipravasi** [comment]
Issue number 1,2,3,5,6 - fixed and validated on the test. 
Searching for an employee through employee id will be an enhancement and need time to figure out a way. Searching for an employee with a name is working fine.

**Comment by steffipravasi** [comment]
@jizhaogit can we change the message to : No goals are currently being shared with you.
![Screenshot 2023-05-18 at 7.00.52 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8c3fe02f-3f09-4854-8da0-8b51da786cac)

**Comment by steffipravasi** [comment]
Message changed and validated on test. 
![Screenshot 2023-05-18 at 9.09.19 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/79dc36a2-c6ea-4a52-8800-9171881e2cd6)
Ticket ready for PO review.
