### ISSUE TITLE
HR Admin > Goal Bank: number of employee rows displayed doesn't match number displayed on goal bank list view 

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#909]
Environment: PROD

Goals created in goal bank and assigned to 640 or 643 employees

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/4a0d9f4d-6adf-47af-acc3-8490145607f2)

<br>
As Sys Admin, when I click on the individual goal audience I see the same number of employee rows (640 or 643). As HR Admin, when I click on the individual goal audience I see 600 or 603 rows. It looks like 40 employee rows are missing for HR Admin view. Any idea why?

**Comment by Travis-A-Clark** [comment]
@telusdcinco Does it make sense to look at this during this sprint? Or should it go with next sprint?

**Comment by telusdcinco** [comment]
Individual Audience and Business Unit Audience counts fixed.  Changes are related to #796.  Added dependency for #796.

**Comment by steffipravasi** [comment]
Not able to add any new goal to the goal bank. Site gives an error.
USer: HRadmin: Nicole Couture
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/General/Testing/909.mov?csf=1&web=1&e=S4jdxd

**Comment by telusdcinco** [comment]
@steffipravasi Issue resolved in Test

**Comment by telusdcinco** [comment]
@steffipravasi The orgs have been fixed in Test.  Please reconfirm.

**Comment by steffipravasi** [comment]
The number of individuals displayed in the Individual Audiences matches for HR and Sys admin
Although, there can be a difference in the number of entries seen in HR admin, because the remaining 50 employees are from the org BC PSA to which the HR admin does not have access to.
![Screenshot 2023-05-11 at 2.40.24 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e367b990-5518-43b0-8a4e-4efa67059f09)
@Travis-A-Clark Is this case acceptable, or we would want to display the entries of users assigned to that goal regardless of the access to orgs?

**Comment by Travis-A-Clark** [comment]
@steffipravasi The HR Admin should only see stats related to the orgs they have access to. So, I think this is behaving correctly. Thanks!

**Comment by steffipravasi** [comment]
Would wait to vaildate this ticket one more time after the issue with assigning access is fixed.

**Comment by steffipravasi** [comment]
Ticket validated and numbers for Hr admin matches with Sys admin for individual audiences in Goal bank.
Moving for PO review.
