### ISSUE TITLE
Troubleshoot performance issues in TEST environment

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#922]
The TEST environment has slowed considerably and has caused performance lags, ajax errors, and 504 errors when pages won't load. Overnight processes are also running far slower than they used to.

We need to:
- Clean up the TEST environment and remove any unneeded instances, databases, files, etc.
- Request additional computing resources for the TEST environment from CITZ; they have indicate they can provide more computing power, memory, etc.

This is also related to ticket #904 since we intend to spin up a training sandbox instance of the app in the TEST environment as well. We can't do that until we optimize the environment and get the proper resources.

**Comment by Abuchana** [comment]
@kkapoor-fresh can you please provide an update about progress on this ticket? Thank you!

**Comment by kkapoor-fresh** [comment]
@Abuchana  I had a discussion with @telusdcinco the other day and suggested that performance degradation in the application could be due to a large number of factors like
1. Slow DB Queries - Indexing, partitioning etc.
2. Unoptimized code
3. Application unable to handle multithreading properly.
4. Improper Resource allocation - Inadequate CPU, memory
5. Network bandwidth while pushing to and pulling from ODS
6. Others.

We need to list out the process/job/code which are showing slowness and understand where the bottleneck lies and fix it accordingly. 
@telusdcinco please check what processes you are seeing a degradation in and  if there is throttling at the application or database side. From an infrastructure perspective, I don't think I am seeing any unusual activity as far as in the way CPU or memory is being used currently.

**Comment by telusdcinco** [comment]
Warren's comment below in Rocketchat:

_

> I think we will need to make a consensus pretty quickly on what we will do to prevent disk issues in each environment.
> 
> 
> In both prod and dev we could be looking at getting a crash [soon]. We can easily allocate capacity from web-app-storage, but maybe we can just maintain a < 3GB database using maintenance scripts instead? We should try to incorporate retention policies for each namespace in calculating the mid to long-term capacity...wile trying to minimize over-requesting.
> 
> Just off the top of my head:
> 
> dev-mysql: 10GB capacity (< 6 used)
> dev-web-app: 2GB cap (< 1 used)
> 
> test-mysql: match prod
> test-web-app: match prod
> 
> prod-mysql: 5GB (< 3 used)
> prod-web-app: 1GB (< 50MB used)
> 
> This will add 1 GB for prod-mysql and 4GB to dev-mysql, and reduce test-mysql by 3GB, and dev, test and prod web-app-storage by 71GB. In my calculation, that saves 69GB of capacity for the cluster.
> 
> 
> I figure dev will require more capacity for debug logging, but maybe with some reasonably aggressive pruning, we can keep that down too.
> 
> Let me know what you guys think, and if you have any recommendations on how to save space...or any reason we may need more instead.



_

**Comment by telusdcinco** [comment]
DB Issue fixed in Dev/Test.

A view was failing in Dev/Test for the past few days and is causing the DB backups to fail.
![image.png](https://images.zenhubusercontent.com/60e88ef619e4760c8b3ee8bb/fc2a5d96-599e-4c4c-b9a7-2d2b5c837dab)

This required for the view to be dropped and recreated.  There may have been an issue in the creation of the view.

Once the view was fixed PDP can now complete the DB backup in Dev and Test.  We are able to analyze and found the DB size to be too big.  Further analysis revealed that there was a lot of logs generated over the months that has taken uyp a lot of storage space.

Ticket #951 was created to address the process logs generated.  The daily process will delete older than x number of days.  By default, it will retain 7 days of process audit logs.  The x days is configurable and we can set it to a high number for now until a decision is finalized for the retention period for process audit logs.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Can we move this ticket to done and focus next steps on ticket #951? Anything else we need to track / fix in this ticket?

**Comment by warrenchristian1telus** [comment]
We are still using 3.35 of 4 GB of MySQL data in prod. 4.94 of 6 GB in dev. I think we should either confirm that automated log rotations/trimming, etc. are sufficient to ensure that we won't [ever] run out of space, Or add more space. Or possibly both just to be safe.

@telusdcinco Do we have a good idea of what future traffic / storage requirements will be? When we go live, will it increase logs significantly, and if so, could we need more room even though we have implemented retention policies?

Also, do we have our retention policies set somewhere? We should probably have it documented where (and how) we can manage this for automated log trimming, etc.. Is this already included in the repo?

**Comment by telusdcinco** [comment]
@warrenchristian1telus PDP already contains all 40K employees on the system.  Although, only 4K are part of the pilot group which is currently the using the application.  The rest will be using the system in July.  There will definitely be an increase in storage requirement but may not be significant.

**Comment by telusdcinco** [comment]
Meeting with Kunal, Warren, Ji, Travis on May 29, to discuss Test issues.

- Test deployment issue resolved.  Pending validation.
- There is no backup for Training.  New ticket to be created for setting backup for Training.
- Training PVC reset from 25GB to 4GB
