### ISSUE TITLE
Sys Admin > Auditing - updates to improve accuracy and usability

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#928]
As per discussion with the product team, we would like to make a number of enhancements to the audit log generated and stored in the PDP.

### 1. Audit entries should be attributed to the user that was originally authorized into the platform.
**Current Situation**

Travis Clark logs in to the platform. He goes to the My Team page, clicks on an employee's profile, and makes a comment on an employees goal or signs off on a conversation. Those actions will be attributed to the other employee, even though it was Travis who did them. The front end accurately reflects that it was Travis (the comment shows up with his name and the sign-off shows up correctly) but the audit log shows these as actions of the employee since Travis was viewing that employee's profile when he did them.

**Desired Solution**

We rely on the original authorization to accurately track the actions of the user. Even if that user views another profile.

### 2. The audit table should be easier to search and understand
If possible, please:
- Add audit ID search function
- Use Employee ID instead of User ID in the table and results (admins have no idea of who User IDs belong to)

**Comment by Travis-A-Clark** [comment]
@jp-Telus I think this looks good. Thanks for the quick turnaround!

A couple of suggestions:
1. Move "Original User" to the second column and change to the name to just "User"
2. Move "Audit User" to the third column and change the the name to "Profile"

Is it possible to apply the original user logic looking backwards at past events, or can we only track this with new events created after we implement the change?

Thanks again!

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Good suggestion. The program was updated and deployed on DEV region. 

Unfortunately, the auditing addon module doesn't capture this original login user information until this customization added, the "audits" table doesn't have the information to display.

James

**Comment by jp-Telus** [comment]
@telusdcinco , 

When you has chance, please kindly perform a code review. I used a branch called "bugfix-928". Once you approve, I will try to merge with Test region.

Thank you.

**Comment by jp-Telus** [comment]
@Travis-A-Clark  ,  The latest program was migrated to TEST region and ready for testing, Thank you.

@telusdcinco, Thank you for the code review. :)

Additional Migration Step:
1) php artisan migrate

**Comment by jp-Telus** [comment]
@Travis-A-Clark , I have noticed that the "switch Identity" function under system administrator, the login user couldn't captured by the new customization, since the original login user id stored on difference session data called "existing_user_id". I have to enhance the program to handle this "switch identity. 

For example, login as system admin  and switch identify to 'Janine Cox', then add a new conversation

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/27e2f231-e156-471f-ad41-569d3df1667f)

Note: In addition, the search field title was updated to the new result columns

You could test this out in TEST region now. 

Thank you
