### ISSUE TITLE
Clone PROD environment as baseline in TEST for performance testing

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#943]
Related to ticket #922 re: performance issues.

**Current Scenario**

PO is not comfortable pushing any new code from TEST to PROD because of the significant performance issues currently happening in the TEST environment. PO does not want to replicate these performance issues in the PROD space.

Concept is to clone current PROD code and create it as a fresh instance in TEST and then:
1.  Check performance between PROD and TEST instances of the same code in different environment. If TEST is still significantly worse, it is likely to be an environment issue.
2.  If they behave similarly in step 1, then reintroduce code changes from DEV, monitoring for performance impacts, to try to identify code or queries that are impacting performance.

**Comment by telusdcinco** [comment]
@Travis-A-Clark The restore Prod code to Test was attempted yesterday.  Accessing Test showed 500 errors and attempts made to push changes from Dev to temp Test proved difficult.  After a couple of hours tinkering, partial page load test shows quick loads similar to prod.  New code was not tested as resulting 500 errors showed up, may be due to underlying table/data changes in Test environment.
Test was restored, and changes to temp Test was reverted.  The slowness may be attributed to the new 5 level org coming from the new org tree.  New indeces was added yesterday, but may require additional work to improve page loading performance.
